"""
Fifty campaign messages in the founder's own voice.

WHY A FOUNDER'S VOICE
---------------------
A message from "the team" reads like marketing; a short note from the person
who started the shop reads like a favour. What makes these convert:

  * first person, signed by a real person ("I", not "we")
  * ONE detail only this customer could recognise: the product THEY bought,
    how many times they have ordered
  * a suggestion that is true about them: what people who bought the same
    thing also bought (Apriori / co-buyers), or else the shop's most-bought
    product they do not already own, said as exactly that
  * one offer, one code, one date, one thing to do
  * short: a phone screen, no scrolling

HOW A MESSAGE IS PUT TOGETHER (campaign_writer.message_for)
---------------------------------------------------------
    _A personal note from Harsh, founder of Rang Studio_      header
    open                       greeting (never leans on a product)
    bought | loyal             their product; `loyal` when 3+ orders
    pair | best                the suggestion, worded by where it came from
    offer | none               the code and date, or no-discount line
    (seller's note)
    CTA                        shop link with the code applied, or, with no
                               website, "reply with your code" + chat link
    close + sign-off

Parts that have nothing true to say are left out, so a customer with no
known product still gets a whole message, never a sentence with a hole.

VARIABLES
---------
{name} {product} {pick} {offer} {code} {expiry} {brand} {occasion} {orders}

Fifty voices: 12 win-back, 8 festival/occasion, 6 each for second order,
goes-well-with, restock, VIP and thank-you.
"""
from __future__ import annotations

WINBACK = [
    {"open": "Hi {name}, it's been a little while, and I noticed.",
     "bought": "You picked the {product} from us, and I've wondered since whether you loved it.",
     "loyal": "You've ordered from us {orders} times, and I genuinely miss seeing your name come in.",
     "pair": "Many people who bought the {product} went on to get the {pick}, and I think you'd love it too.",
     "best": "If you fancy something new, the {pick} is what most of our customers are ordering right now.",
     "offer": "So here's {offer} from me. Your personal code is *{code}*, valid till {expiry}.",
     "none": "Whenever you're ready, I'd love to have you back.",
     "close": "Thank you for being one of the people who keep this little shop going.",
     "subject": "{name}, I noticed you've been away"},
    {"open": "Hi {name}, I'm writing this one myself because I wanted to ask you something.",
     "bought": "Was the {product} everything you hoped it would be?",
     "loyal": "After {orders} orders, you're one of the customers I think of when I add something new.",
     "pair": "If you liked the {product}, the {pick} is the one customers like you usually go for next.",
     "best": "Our most-loved piece at the moment is the {pick}, and I'd love to know what you think.",
     "offer": "I've set aside {offer} for you with the code *{code}*. It works till {expiry}.",
     "none": "If anything wasn't right, just tell me and I'll make it right.",
     "close": "Honest replies are always welcome, they help me more than you know.",
     "subject": "A quick question from me, {name}"},
    {"open": "Hello {name}, I hope you've been well.",
     "bought": "I still remember packing your {product}.",
     "loyal": "You've been with us for {orders} orders now, and that means a lot to a small brand like mine.",
     "pair": "Customers who chose the {product} have been pairing it with the {pick}. I think it would suit you.",
     "best": "The {pick} has quietly become our customers' favourite, and you haven't tried it yet.",
     "offer": "To welcome you back: {offer} with your code *{code}*, till {expiry}.",
     "none": "I'd be so happy to pack your next order too.",
     "close": "Wishing you a lovely week.",
     "subject": "I hope you've been well, {name}"},
    {"open": "Hi {name}, this is a short note, and it's only for you.",
     "bought": "You bought the {product} from us, and you clearly have good taste.",
     "loyal": "{orders} orders in, you know us better than most.",
     "pair": "People who bought the {product} kept coming back for the {pick}.",
     "best": "You might like the {pick}. It's the one most of our customers buy.",
     "offer": "Your code *{code}* gives you {offer} on your next order. It's personal to you and ends on {expiry}.",
     "none": "Have a look at what's new whenever you have a minute.",
     "close": "No pressure at all. I just didn't want you to miss it.",
     "subject": "Only for you, {name}: {offer}"},
    {"open": "Hi {name}, can I be honest with you?",
     "bought": "Customers who love the {product} usually come back, so I wondered if we let you down somewhere.",
     "loyal": "You've ordered {orders} times, and when a regular goes quiet I always wonder why.",
     "pair": "If you're up for something new, people who bought the {product} adore the {pick}.",
     "best": "And if you'd like something different, the {pick} is our most-ordered piece.",
     "offer": "I'd love another chance, so here's {offer}: code *{code}*, valid till {expiry}.",
     "none": "If something went wrong, reply and tell me. I read every message.",
     "close": "Either way, thank you for giving us a try.",
     "subject": "Can I be honest, {name}?"},
    {"open": "Dear {name}, it's been a while since we heard from you.",
     "bought": "I hope the {product} is still a favourite.",
     "loyal": "Thank you for every one of your {orders} orders. I don't take them for granted.",
     "pair": "Since you have the {product}, take a look at the {pick}: it's the natural next step our customers take.",
     "best": "Our best seller, the {pick}, is back and I thought of you.",
     "offer": "I've made a code just for you, *{code}*, for {offer}. It's good till {expiry}.",
     "none": "We'd love to see you again soon.",
     "close": "With warmth, and gratitude.",
     "subject": "{name}, a little something I made for you"},
    {"open": "Hi {name}! I was going through our customer list today, and your name made me smile.",
     "bought": "The {product} you picked is one of my favourites too.",
     "loyal": "{orders} orders! You're one of our regulars, and I'm grateful for it.",
     "pair": "People who bought the {product} also fell for the {pick}. I have a feeling you would too.",
     "best": "Have you seen the {pick}? It's what everyone has been ordering.",
     "offer": "Here's {offer} as a small thank-you. Code *{code}*, till {expiry}.",
     "none": "Come and see what's new whenever you like.",
     "close": "Hope to hear from you soon.",
     "subject": "Your name made me smile today, {name}"},
    {"open": "Hi {name}, I know your inbox is busy, so I'll keep this short.",
     "bought": "You liked the {product}.",
     "loyal": "You've ordered {orders} times.",
     "pair": "Most people who bought it also got the {pick}.",
     "best": "Our customers' favourite right now is the {pick}.",
     "offer": "You get {offer} with code *{code}* until {expiry}.",
     "none": "Something new is waiting for you.",
     "close": "That's it. Thank you, truly.",
     "subject": "{offer} for you, {name} (short note)"},
    {"open": "Hello {name}, I miss customers like you, and I mean that.",
     "bought": "I hope the {product} turned out to be worth it.",
     "loyal": "You trusted us {orders} times. That trust is the reason this shop still exists.",
     "pair": "If you'd like something to go with your {product}, our customers swear by the {pick}.",
     "best": "Something many of our customers love that you haven't tried yet: the {pick}.",
     "offer": "I want to say thank you properly: {offer} with *{code}*, valid till {expiry}.",
     "none": "Whenever you're ready, we're right here.",
     "close": "Thank you for being part of our story.",
     "subject": "I miss customers like you, {name}"},
    {"open": "Hi {name}, a small note from the person behind {brand}.",
     "bought": "Every {product} we send out is checked by hand, including yours.",
     "loyal": "Across your {orders} orders, I hope we've earned a place in your favourites.",
     "pair": "Customers who picked the {product} often come back for the {pick}. I'd love you to see it.",
     "best": "The {pick} is the piece customers order most, and I think you'd like it.",
     "offer": "Your next one comes with {offer}. Just use *{code}* before {expiry}.",
     "none": "I'd love to make your next order just as special.",
     "close": "Made with care, always.",
     "subject": "A note from the person behind {brand}"},
    {"open": "Hey {name}! It's been too long.",
     "bought": "Fancy another {product}?",
     "loyal": "You've ordered {orders} times, so you know the drill by now.",
     "pair": "Or try the {pick}: that's what most people who bought the {product} did next.",
     "best": "Or try the {pick}, it's our most popular piece right now.",
     "offer": "Either way, {offer} is yours with code *{code}* (till {expiry}).",
     "none": "Take a look whenever you're free.",
     "close": "See you soon, I hope!",
     "subject": "It's been too long, {name}"},
    {"open": "Hi {name}, I'd love to welcome you back.",
     "bought": "Since you chose the {product}, I've kept you in mind with everything new we've made.",
     "loyal": "With {orders} orders behind you, you're family here.",
     "pair": "The {pick} is the one people who loved the {product} keep telling me about.",
     "best": "The {pick} is the favourite of most of our customers, and I'd love you to see it.",
     "offer": "Welcome back with {offer}. Your code: *{code}*, until {expiry}.",
     "none": "The door is always open.",
     "close": "Thank you for shopping small with us.",
     "subject": "Welcome back, {name}"},
]

FESTIVAL = [
    {"open": "Hi {name}, {occasion} is almost here, and I wanted you to hear from me first.",
     "bought": "You loved the {product}, so I think you'll love what we've made for {occasion}.",
     "loyal": "You've ordered {orders} times, so you get the first look, before anyone else.",
     "pair": "For {occasion}, the {pick} is what people who bought the {product} are choosing.",
     "best": "For {occasion}, our most-ordered piece is the {pick}.",
     "offer": "Celebrate with {offer}. Your code is *{code}*, valid till {expiry}.",
     "none": "Have a look at what's new for {occasion}.",
     "close": "Wishing you and your family a wonderful {occasion}.",
     "subject": "Happy {occasion}, {name}: {offer} inside"},
    {"open": "Happy {occasion}, {name}!",
     "bought": "I hope the {product} makes an appearance this season.",
     "loyal": "Thank you for {orders} orders this year and before. It's been a joy.",
     "pair": "If you're shopping for {occasion}, people who bought the {product} are loving the {pick}.",
     "best": "If you're shopping for {occasion}, the {pick} is our customers' top pick.",
     "offer": "Here's my {occasion} gift to you: {offer} with *{code}*, till {expiry}.",
     "none": "I'd love to be a small part of your {occasion}.",
     "close": "With warm wishes from all of us.",
     "subject": "A {occasion} gift from me, {name}"},
    {"open": "Hi {name}, {occasion} always reminds me why I started {brand}.",
     "bought": "Customers like you, who chose the {product}, made this year possible.",
     "loyal": "And you've been here for {orders} orders, so this one is for you.",
     "pair": "For the season, the {pick} is the favourite among people who bought the {product}.",
     "best": "This season, the {pick} is the piece customers are ordering most.",
     "offer": "For {occasion}: {offer}, code *{code}*, valid till {expiry}.",
     "none": "Celebrate with something special from us.",
     "close": "Thank you, from the bottom of my heart.",
     "subject": "{occasion}, and why I started {brand}"},
    {"open": "Hi {name}, before the {occasion} rush begins, a quick heads-up.",
     "bought": "Since you bought the {product}, I've kept your size and style in mind.",
     "loyal": "As one of our regulars ({orders} orders!), you're at the front of the line.",
     "pair": "The {pick} is the one most people with a {product} add for {occasion}.",
     "best": "The {pick} tends to sell out first around {occasion}.",
     "offer": "Your personal {occasion} code *{code}* gives you {offer} until {expiry}.",
     "none": "Order early and it reaches you well in time.",
     "close": "Order early so it reaches you in time.",
     "subject": "Before the {occasion} rush, {name}"},
    {"open": "Dear {name}, wishing you a joyful {occasion}.",
     "bought": "I hope the {product} is part of the celebrations.",
     "loyal": "You've shopped with us {orders} times, and you've made our year brighter.",
     "pair": "To go with your {product}, our customers are choosing the {pick} this {occasion}.",
     "best": "Our most-loved piece this {occasion}: the {pick}.",
     "offer": "Take {offer} on me with *{code}*, valid till {expiry}.",
     "none": "Have a look at what we have for {occasion}.",
     "close": "Celebrate well, and stay safe.",
     "subject": "Wishing you a joyful {occasion}, {name}"},
    {"open": "Hi {name}! {occasion} is the time to treat yourself, and the people you love.",
     "bought": "You already know the {product}.",
     "loyal": "You've treated yourself with us {orders} times, so you know we deliver.",
     "pair": "This time, the {pick} is the gift people who bought the {product} keep choosing.",
     "best": "This time, why not the {pick}? It's our best seller.",
     "offer": "Gift or for you, it's {offer} with code *{code}* till {expiry}.",
     "none": "Gift or for you, I'd love to help you choose.",
     "close": "Just reply if you'd like me to help you choose.",
     "subject": "Treat yourself this {occasion}, {name}"},
    {"open": "Hi {name}, I'm sending this to only a few of our customers for {occasion}.",
     "bought": "You're on the list because you chose the {product}.",
     "loyal": "And because you've ordered {orders} times.",
     "pair": "I think the {pick} is your next favourite. It's what people with your taste bought.",
     "best": "I think the {pick} would be perfect. It's our most-ordered piece.",
     "offer": "Your private code is *{code}* for {offer}. It ends on {expiry}.",
     "none": "Come and see what's new before everyone else.",
     "close": "Happy {occasion} to you.",
     "subject": "Only a few customers get this, {name}"},
    {"open": "Hello {name}, {occasion} greetings from me and everyone at {brand}.",
     "bought": "Thank you for trusting us with your {product}.",
     "loyal": "Thank you for trusting us {orders} times.",
     "pair": "If you'd like to add to it, the {pick} is what most people who bought the {product} chose next.",
     "best": "If you'd like something new, the {pick} is loved by our customers.",
     "offer": "Here's {offer} to celebrate. Code *{code}*, valid till {expiry}.",
     "none": "Wishing you the very best this season.",
     "close": "May this {occasion} bring you everything good.",
     "subject": "{occasion} greetings from {brand}"},
]

SECOND_ORDER = [
    {"open": "Hi {name}, thank you for your first order with us. I still remember it.",
     "bought": "I hope the {product} arrived just the way you hoped.",
     "pair": "Most people who bought the {product} come back for the {pick}.",
     "best": "Customers who come back usually pick the {pick} next.",
     "offer": "For your second order, I'm giving you {offer}. Code *{code}*, till {expiry}.",
     "none": "I'd love to pack your second order myself.",
     "close": "Reply anytime, it comes straight to me.",
     "subject": "Thank you for your first order, {name}"},
    {"open": "Hi {name}, a first order is a leap of faith, and you took it with us.",
     "bought": "How are you finding the {product}?",
     "pair": "If you liked it, the {pick} is what most of our customers who bought the {product} get next.",
     "best": "If you'd like to try more, the {pick} is our most-loved piece.",
     "offer": "To make your second order easy: {offer} with *{code}*, valid till {expiry}.",
     "none": "Tell me what you think, good or bad. I read everything.",
     "close": "Thank you for trusting a small brand.",
     "subject": "How are you finding it, {name}?"},
    {"open": "Hello {name}, I hope you're enjoying your first {brand} order.",
     "bought": "The {product} is one of my personal favourites.",
     "pair": "It goes beautifully with the {pick}, which is why so many customers buy both.",
     "best": "The {pick} is the piece most customers add to their collection next.",
     "offer": "Here's {offer} on your next one: *{code}*, until {expiry}.",
     "none": "I'd love to help you find your next favourite.",
     "close": "Warmly, and with thanks.",
     "subject": "Your next favourite, {name}"},
    {"open": "Hi {name}, quick note from me.",
     "bought": "Your {product} was one of the orders I was happiest to send this month.",
     "pair": "People who bought the {product} often come back for the {pick}. Worth a look.",
     "best": "Worth a look: the {pick}, our most popular piece.",
     "offer": "And {offer} is waiting for you with *{code}* (good till {expiry}).",
     "none": "Come back anytime, there's always something new.",
     "close": "Thank you for being one of our newest customers.",
     "subject": "A quick note from me, {name}"},
    {"open": "Hi {name}, welcome to the {brand} family. I mean that.",
     "bought": "I'd love to hear how the {product} is working out.",
     "pair": "When you're ready for more, the {pick} is the next thing people who loved the {product} bought.",
     "best": "When you're ready for more, start with the {pick}. Customers love it.",
     "offer": "Here's {offer} for when you are: *{code}*, till {expiry}.",
     "none": "Whenever you're ready, I'm here to help.",
     "close": "So glad you found us.",
     "subject": "Welcome to the family, {name}"},
    {"open": "Hi {name}, most customers decide after their first order whether a shop is for them.",
     "bought": "I really hope the {product} made the decision easy.",
     "pair": "If it did, the {pick} is the natural next step: people who bought the {product} love it.",
     "best": "If it did, try the {pick} next. It's our best seller.",
     "offer": "Let me make it easier still: {offer} with *{code}*, valid till {expiry}.",
     "none": "And if it didn't, please tell me why.",
     "close": "Either way, thank you for giving us a chance.",
     "subject": "Did we earn your second order, {name}?"},
]

CROSS_SELL = [
    {"open": "Hi {name}, I had an idea for you.",
     "bought": "You have the {product}.",
     "pair": "Nearly everyone who bought it also picked up the {pick}, and they look wonderful together.",
     "best": "The {pick} goes beautifully with it.",
     "offer": "So here's {offer} on the {pick} or anything else: *{code}*, till {expiry}.",
     "none": "Have a look and tell me what you think.",
     "close": "Just a thought from me, no pressure.",
     "subject": "An idea for your {product}, {name}"},
    {"open": "Hello {name}, a tip from someone who sees every order.",
     "bought": "The {product} you bought is one half of our most popular combination.",
     "pair": "The other half is the {pick}. Customers who own both keep coming back.",
     "best": "The other half is the {pick}.",
     "offer": "Complete the pair with {offer}: code *{code}*, valid till {expiry}.",
     "none": "Complete the pair whenever you like.",
     "close": "Happy to send you photos of them together if you'd like.",
     "subject": "Complete the pair, {name}"},
    {"open": "Hi {name}, since you chose the {product}, I thought of you.",
     "bought": "",
     "pair": "Our customers who have the {product} almost always add the {pick}.",
     "best": "The {pick} is the perfect partner for it.",
     "offer": "I've made a code for you: *{code}* for {offer}, till {expiry}.",
     "none": "Take a look when you have a moment.",
     "close": "Thank you for being with us.",
     "subject": "I thought of you, {name}"},
    {"open": "Hi {name}! Something that goes perfectly with what you already have.",
     "bought": "You've got the {product}.",
     "pair": "The {pick} is the one most people who bought it come back for.",
     "best": "Meet the {pick}.",
     "offer": "Yours with {offer} using *{code}* until {expiry}.",
     "none": "I think you'll love it.",
     "close": "Reply if you have any questions, I answer myself.",
     "subject": "Made to go with your {product}"},
    {"open": "Dear {name}, a small recommendation, just for you.",
     "bought": "I hope you're still enjoying the {product}.",
     "pair": "People who bought it tell me the {pick} is what made it complete.",
     "best": "The {pick} would complete it beautifully.",
     "offer": "Here's {offer} if you'd like to try it: *{code}*, valid till {expiry}.",
     "none": "Have a look whenever you're ready.",
     "close": "With thanks, as always.",
     "subject": "A recommendation for you, {name}"},
    {"open": "Hi {name}, I noticed something about your order.",
     "bought": "You bought the {product} but not its favourite partner.",
     "pair": "The {pick} is what most customers who bought the {product} also took home.",
     "best": "That's the {pick}.",
     "offer": "So you don't miss out: {offer} with *{code}*, until {expiry}.",
     "none": "Take a look, I think you'll see why.",
     "close": "Thank you for shopping with us.",
     "subject": "You missed its favourite partner, {name}"},
]

RESTOCK = [
    {"open": "Hi {name}, a quick reminder from me.",
     "bought": "It's been about the usual time since your last {product}, so it might be running low.",
     "offer": "Restock with {offer}: code *{code}*, valid till {expiry}.",
     "none": "Reorder whenever you're ready and I'll send it out fast.",
     "close": "Thanks for coming back to us.",
     "subject": "Running low on your {product}, {name}?"},
    {"open": "Hello {name}, I keep track of our regulars so you never run out.",
     "bought": "By my count, your {product} should be nearly finished.",
     "loyal": "You've ordered {orders} times, so I know the {product} is a favourite.",
     "offer": "Here's {offer} on your refill with *{code}*, till {expiry}.",
     "none": "Shall I send another one your way?",
     "close": "Just reply, and I'll handle the rest.",
     "subject": "Time for a refill, {name}?"},
    {"open": "Hi {name}, this is your friendly restock reminder.",
     "bought": "Most customers reorder the {product} around now.",
     "offer": "Your code *{code}* gives you {offer} on it, until {expiry}.",
     "none": "Order now and it'll reach you before you run out.",
     "close": "So you never have to go without.",
     "subject": "Your {product} reminder"},
    {"open": "Hi {name}, I hope I'm not too early.",
     "bought": "It's about time for a new {product}, going by your last order.",
     "loyal": "After {orders} orders, I know you like to stay stocked up.",
     "offer": "To make it easy: {offer} with *{code}*, till {expiry}.",
     "none": "Reorder in a minute, whenever suits you.",
     "close": "Thank you for being a regular.",
     "subject": "Am I too early, {name}?"},
    {"open": "Dear {name}, a small nudge from me.",
     "bought": "Your {product} is probably close to empty by now.",
     "offer": "Here's {offer} for the next one: *{code}*, until {expiry}.",
     "none": "We have fresh stock ready to go.",
     "close": "With thanks for your loyalty.",
     "subject": "A small nudge, {name}"},
    {"open": "Hi {name}, before you run out:",
     "bought": "the {product} you love is in stock and ready to ship.",
     "offer": "Use *{code}* for {offer}, valid till {expiry}.",
     "none": "Reply 'yes' and I'll get it ready for you.",
     "close": "Always happy to keep you stocked.",
     "subject": "Before you run out, {name}"},
]

VIP = [
    {"open": "Hi {name}, you're one of our very best customers, so you hear this first.",
     "bought": "Every time you ordered the {product}, it made my day.",
     "loyal": "{orders} orders. I don't say this lightly: thank you.",
     "pair": "Many customers who love the {product} are also choosing the {pick}.",
     "best": "And the {pick} is the one everyone is talking about.",
     "offer": "As a thank-you, {offer} with *{code}*, till {expiry}.",
     "none": "Before anyone else, I wanted you to know.",
     "close": "You're the reason we keep going.",
     "subject": "You hear this first, {name}"},
    {"open": "Dear {name}, I'm writing to a very small group today, and you're in it.",
     "bought": "Customers who love the {product} as much as you do deserve the first look.",
     "loyal": "With {orders} orders, you're one of our closest customers.",
     "pair": "I think you'll especially love the {pick}.",
     "best": "Keep an eye on the {pick}.",
     "offer": "Your private code is *{code}* for {offer}, until {expiry}.",
     "none": "You get early access before it goes public.",
     "close": "Thank you for everything.",
     "subject": "A very small group, and you're in it"},
    {"open": "Hi {name}, I wanted you to know before anyone else.",
     "bought": "You've been with us since the {product}, and I haven't forgotten.",
     "loyal": "You've placed {orders} orders, and that loyalty deserves something back.",
     "pair": "Since you love the {product}, look out for the {pick}.",
     "best": "The {pick} is the one to watch.",
     "offer": "Use *{code}* for {offer} until {expiry}.",
     "none": "It's yours to see first.",
     "close": "Reply anytime, it comes straight to me.",
     "subject": "Before anyone else, {name}"},
    {"open": "Hi {name}, a thank-you, and a first look.",
     "bought": "Customers who chose the {product}, like you, shaped what we made next.",
     "loyal": "You've ordered {orders} times, and many of our ideas came from customers like you.",
     "pair": "I think the {pick} will be your favourite.",
     "best": "The {pick} is my favourite, and I'd love your opinion.",
     "offer": "Take {offer} with *{code}*, valid till {expiry}.",
     "none": "You're among the first to know.",
     "close": "With real gratitude.",
     "subject": "A thank-you and a first look"},
    {"open": "Hello {name}, VIP doesn't feel like the right word, but you're one of our favourites.",
     "bought": "Your {product} orders are some I remember best.",
     "loyal": "{orders} orders! You're part of this shop's story.",
     "pair": "People who love the {product} have already been asking about the {pick}.",
     "best": "Have a look at the {pick} too.",
     "offer": "So here's {offer} with *{code}*, until {expiry}.",
     "none": "I saved you a first look.",
     "close": "Thank you, truly.",
     "subject": "You're one of our favourites, {name}"},
    {"open": "Hi {name}, early access, just for you.",
     "bought": "Because you loved the {product}, I made sure you're on the first list.",
     "loyal": "With {orders} orders, you've more than earned it.",
     "pair": "And the {pick} is what most people with your taste go for.",
     "best": "And the {pick} is our customers' favourite.",
     "offer": "Code *{code}*: {offer}, valid till {expiry}.",
     "none": "Before it opens to everyone.",
     "close": "Enjoy, and thank you for being with us.",
     "subject": "Early access for you, {name}"},
]

THANK_YOU = [
    {"open": "Hi {name}, thank you for your order. It means more than you might think.",
     "bought": "I hope the {product} is everything you wanted.",
     "offer": "As a thank-you, here's {offer} for next time: *{code}*, valid till {expiry}.",
     "none": "If you love it, would you leave us a quick review? Just reply here, it helps a small shop enormously.",
     "close": "Thank you for supporting a small brand.",
     "subject": "Thank you, {name}"},
    {"open": "Dear {name}, I just wanted to say thank you, personally.",
     "bought": "Your {product} was packed with extra care.",
     "offer": "Here's {offer} on your next order with *{code}*, till {expiry}.",
     "none": "If you have a moment, reply and tell me how you like it, or leave a short review. Your words help other customers choose.",
     "close": "With gratitude.",
     "subject": "A personal thank-you, {name}"},
    {"open": "Hi {name}, your order made my day.",
     "bought": "How are you liking the {product}?",
     "offer": "For next time: {offer} with *{code}*, until {expiry}.",
     "none": "A quick reply with what you think would mean the world to me.",
     "close": "Thank you for choosing us.",
     "subject": "Your order made my day, {name}"},
    {"open": "Hello {name}, thank you for shopping with {brand}.",
     "bought": "I hope the {product} brings you a lot of joy.",
     "offer": "Here's {offer} as a small thank-you: *{code}*, valid till {expiry}.",
     "none": "If you're happy with it, a short review would help us more than any ad.",
     "close": "See you again soon, I hope.",
     "subject": "Thank you for shopping with us, {name}"},
    {"open": "Hi {name}, a big thank-you from me.",
     "bought": "The {product} is one of my favourites, and I'm so glad it's yours now.",
     "offer": "Use *{code}* for {offer} on your next order, till {expiry}.",
     "none": "Would you share a photo or a line about it? Just reply here.",
     "close": "Grateful for customers like you.",
     "subject": "A big thank-you, {name}"},
    {"open": "Hi {name}, every order is a small celebration here, and yours was one.",
     "bought": "I hope you love the {product} as much as I loved sending it.",
     "offer": "Here's {offer} for your next one: *{code}*, until {expiry}.",
     "none": "A two-line review from you would help someone else find us.",
     "close": "Thank you, really.",
     "subject": "Your order was a small celebration"},
]

VOICES = {"winback": WINBACK, "festival": FESTIVAL, "second_order": SECOND_ORDER,
          "cross_sell": CROSS_SELL, "restock": RESTOCK, "vip": VIP, "thank_you": THANK_YOU}
assert sum(len(v) for v in VOICES.values()) == 50

# The one thing to do. With a website the link opens the shop with the code
# already applied. Without one, the customer replies with their code (and, for
# email or a forwarded message, a tracked link opens a chat with the shop).
CTA_SITE = ["Your code is already applied when you shop here: {link}",
            "Tap here and it's applied for you: {link}",
            "Everything is here, with your code already on: {link}"]
CTA_SITE_NONE = ["Have a look here: {link}", "Take a look whenever you like: {link}",
                 "Here's the link: {link}"]
CTA_CHAT = ["To use it, just reply to this message with *{code}* and I'll sort your order out myself.",
            "Reply with your code *{code}* and tell me what you'd like. I'll take care of the rest.",
            "Just send me *{code}* here on WhatsApp and I'll set your order aside."]
CTA_CHAT_NONE = ["Just reply here and I'll help you choose myself.",
                 "Reply to this message and I'll help you personally.",
                 "Send me a message here, I answer myself."]
CHAT_LINK = "Or tap to message me: {chatlink}"
